# Generated by Django 4.0.6 on 2022-07-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abousus',
            name='para1',
            field=models.TextField(blank=True, max_length=3000),
        ),
        migrations.AlterField(
            model_name='abousus',
            name='para2',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
