# Generated by Django 4.0.6 on 2022-07-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0002_alter_abousus_para1_alter_abousus_para2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abousus',
            old_name='para2',
            new_name='aboutus_1',
        ),
        migrations.RemoveField(
            model_name='abousus',
            name='para1',
        ),
        migrations.AddField(
            model_name='abousus',
            name='main_sub_heading',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
