# Generated by Django 4.0.6 on 2022-07-24 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0004_abousus_aboutus_2_alter_abousus_aboutus_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='abousus',
            name='profile_Image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_Image'),
            preserve_default=False,
        ),
    ]
