# Generated by Django 4.0.6 on 2022-07-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0007_skill_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=60)),
            ],
        ),
    ]
