# Generated by Django 4.0.6 on 2022-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0008_service_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_name', models.CharField(blank=True, max_length=300)),
                ('video_Link', models.CharField(blank=True, max_length=300)),
                ('code_Link', models.CharField(blank=True, max_length=300)),
                ('content', models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
