# Generated by Django 4.0.6 on 2022-07-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0010_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Certificate_name', models.CharField(blank=True, max_length=300)),
                ('Certificate_image', models.ImageField(blank=True, upload_to='Certificate')),
                ('content', models.TextField(blank=True, max_length=2000)),
            ],
        ),
    ]
