# Generated by Django 4.0.6 on 2022-07-25 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0011_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('hiring_for', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True, max_length=2505)),
            ],
        ),
    ]
