# Generated by Django 4.0.6 on 2022-07-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0012_hiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='hiring_for',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='message',
            field=models.TextField(max_length=2505),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
