# Generated by Django 4.0.6 on 2022-07-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0015_mycv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abousus',
            name='aboutus_1',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='abousus',
            name='aboutus_2',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='abousus',
            name='main_sub_heading',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='content',
            field=models.TextField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, max_length=10000),
        ),
    ]
