# Generated by Django 4.0.6 on 2022-07-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0017_experience_alter_abousus_aboutus_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='content',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=models.TextField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, max_length=20000),
        ),
    ]
