# Generated by Django 4.0.6 on 2022-08-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfoliowork', '0018_alter_certificate_content_alter_experience_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=25005),
        ),
        migrations.AlterField(
            model_name='experience',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='hiring',
            name='message',
            field=models.TextField(max_length=25505),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
